// Batch Number 83
// Suyash Kumar 2014A7PS053P
// Siddharth Agarwal 2014A7PS025P
#include <stdio.h>
#include <stdlib.h>
#include "symbolTable.c"

char filename[100];
char parseTreeOutFile[100];

void printProgress()
{
	printf("(a) First and Follow Sets Hard Coded\n");
	printf("(b) Both lexical and syntax analysis modules implemented\n\n\n");
}

void getOptions()
{
	int choice;
	printf("Press option for the defined task\n1 : For removal of comments ‐ print the comment free code on the console\n2 : for printing the token list (on the console) generated by the lexer.\nEach token appears in a new line alongwith the corresponding lexeme and linenumber.\n3 : for parsing to verify the syntactic correctness of the input source code\n4 : for creating the parse tree and printing it appropriately\n5: for creating symbol table\n");

	

		// printf("new5");
		// line_num = 1;
	scanf("%d",&choice);
	FILE * fopenParseTree; 
				
		int exit = 0;
		switch(choice)
		{
			case 1:
				// initialise(filename);
				printProgramWithoutComments(filename);
				break;
			case 2:
				// initialise(filename);
				mainOfLexer(filename);
				printLinkedList();
				break;
			case 3:
				fopenParseTree = fopen(parseTreeOutFile, "w+");

				// initialise(filename);
				mainOfLexer(filename);
				// printLinkedList();
				// parserSiddharth();
				parsing();
				fclose(fopenParseTree);
				// printf()
				break;
			case 4:
				// initialise(filename);
				mainOfLexer(filename);
				parsing();
				// printParseTree(parseTreeOutFile);
				printInorder(parserTree, fopenParseTree);

				printf("Parse Tree has been created in the passed file\n");
				break;

			case 5:
				// initialise(filename);
				mainOfLexer(filename);
				parsing();
				// printParseTree(parseTreeOutFile);
				mainOfSymbolTable();
			default:
				printf("You put in an invalid choice..try again\n");
				break;
		};	



	
}

int main(int argc, char *argv[])
{
	if(argc == 3)
	{
		strcpy(filename, argv[1]);
		strcpy(parseTreeOutFile,argv[2]);
		// filename = argv[1];
		printf("%s",filename);
		// parseTreeOutFile = argv[2];

		printProgress();
		getOptions();
	}
	else
	{
		printf("You need to give 2 arguments!\n");
		printf("%d", argc);
	}
}